package com.ecoaccess.dao;

import java.sql.*; import java.util.*;
import com.ecoaccess.model.*; import com.ecoaccess.model.Enums.*;

public class AccountDao {
    public Optional<Passenger> passengerByMobile(String mobile) { return onePassenger("select * from passengers where mobile=?", mobile); }
    public Optional<Passenger> passengerById(String id) { return onePassenger("select * from passengers where id=?", id); }
    private Optional<Passenger> onePassenger(String sql, String value) { try(Connection c=Database.connection(); PreparedStatement p=c.prepareStatement(sql)){p.setString(1,value);try(ResultSet r=p.executeQuery()){return r.next()?Optional.of(passenger(r)):Optional.empty();}}catch(SQLException e){throw Database.failure(e);} }
    public void insertPassenger(Connection c, Passenger x) throws SQLException { try(PreparedStatement p=c.prepareStatement("insert into passengers(id,name,mobile,email,password_hash,points) values(?,?,?,?,?,?)")){p.setString(1,x.getId());p.setString(2,x.getName());p.setString(3,x.getMobile());p.setString(4,x.getEmail());p.setString(5,x.getPasswordHash());p.setInt(6,x.getPoints());p.executeUpdate();} }
    public void updatePassenger(Connection c, Passenger x) throws SQLException { try(PreparedStatement p=c.prepareStatement("update passengers set name=?,email=?,password_hash=?,points=? where id=?")){p.setString(1,x.getName());p.setString(2,x.getEmail());p.setString(3,x.getPasswordHash());p.setInt(4,x.getPoints());p.setString(5,x.getId());p.executeUpdate();} }
    public Optional<Staff> staffByEmployeeId(String employeeId) { try(Connection c=Database.connection();PreparedStatement p=c.prepareStatement("select * from staff where lower(employee_id)=lower(?)")){p.setString(1,employeeId);try(ResultSet r=p.executeQuery()){return r.next()?Optional.of(staff(r)):Optional.empty();}}catch(SQLException e){throw Database.failure(e);} }
    public Optional<Staff> staffById(String id) { try(Connection c=Database.connection();PreparedStatement p=c.prepareStatement("select * from staff where id=?")){p.setString(1,id);try(ResultSet r=p.executeQuery()){return r.next()?Optional.of(staff(r)):Optional.empty();}}catch(SQLException e){throw Database.failure(e);} }
    public List<Staff> staff(String search) { return staffList("select * from staff where lower(name) like lower(?) or lower(employee_id) like lower(?) order by employee_id", search); }
    public List<Staff> availableStaff() { return staffList("select * from staff where status='Available' order by employee_id", ""); }
    private List<Staff> staffList(String sql,String search){try(Connection c=Database.connection();PreparedStatement p=c.prepareStatement(sql)){if(sql.contains("like")){p.setString(1,"%"+search+"%");p.setString(2,"%"+search+"%");}try(ResultSet r=p.executeQuery()){List<Staff> out=new ArrayList<>();while(r.next())out.add(staff(r));return out;}}catch(SQLException e){throw Database.failure(e);}}
    public void insertStaff(Staff x){try(Connection c=Database.connection()){insertStaff(c,x);}catch(SQLException e){throw Database.failure(e);}}
    public void insertStaff(Connection c,Staff x)throws SQLException{try(PreparedStatement p=c.prepareStatement("insert into staff(id,employee_id,name,password_hash,status) values(?,?,?,?,?)")){p.setString(1,x.getId());p.setString(2,x.getEmployeeId());p.setString(3,x.getName());p.setString(4,x.getPasswordHash());p.setString(5,x.getStatus().label());p.executeUpdate();} }
    public void updateStaff(Staff x){try(Connection c=Database.connection();PreparedStatement p=c.prepareStatement("update staff set name=?,password_hash=?,status=? where id=?")){p.setString(1,x.getName());p.setString(2,x.getPasswordHash());p.setString(3,x.getStatus().label());p.setString(4,x.getId());p.executeUpdate();}catch(SQLException e){throw Database.failure(e);}}
    public void deleteStaff(String id){try(Connection c=Database.connection();PreparedStatement p=c.prepareStatement("delete from staff where id=?")){p.setString(1,id);p.executeUpdate();}catch(SQLException e){throw Database.failure(e);}}
    public Optional<Admin> adminByEmail(String email){try(Connection c=Database.connection();PreparedStatement p=c.prepareStatement("select * from admins where lower(email)=lower(?)")){p.setString(1,email);try(ResultSet r=p.executeQuery()){return r.next()?Optional.of(admin(r)):Optional.empty();}}catch(SQLException e){throw Database.failure(e);}}
    private Passenger passenger(ResultSet r)throws SQLException{return new Passenger(r.getString("id"),r.getString("name"),r.getString("mobile"),r.getString("email"),r.getString("password_hash"),r.getInt("points"));}
    private Staff staff(ResultSet r)throws SQLException{return new Staff(r.getString("id"),r.getString("employee_id"),r.getString("name"),r.getString("password_hash"),StaffStatus.valueOf(r.getString("status").toUpperCase()));}
    private Admin admin(ResultSet r)throws SQLException{return new Admin(r.getString("id"),r.getString("name"),r.getString("email"),r.getString("password_hash"));}
}
