package com.ecoaccess.dao;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.sql.Types;
import java.util.*;
import com.ecoaccess.model.*;
import com.ecoaccess.model.Enums.*;

public class BookingDao {
    public List<Booking> list(String passengerId,String staffId,String search,String service,String status){return query("select * from bookings where (? is null or passenger_id=?) and (? is null or (staff_id=? or staff_id is null)) and lower(id||' '||passenger||' '||station) like lower(?) and (? is null or service=?) and (? is null or status=?) order by service_date desc,service_time desc",passengerId,staffId,search,service,status);}
    public List<Booking> all(String search,String service){return query("select * from bookings where lower(id||' '||passenger||' '||station||' '||service) like lower(?) and (? is null or service=?) order by service_date desc,service_time desc",null,null,search,service,null);}
    private List<Booking> query(String q,String passengerId,String staffId,String search,String service,String status){try(Connection c=Database.connection();PreparedStatement p=c.prepareStatement(q)){int i=1;if(q.contains("(? is null or passenger_id=?")){p.setString(i++,passengerId);p.setString(i++,passengerId);p.setString(i++,staffId);p.setString(i++,staffId);p.setString(i++,"%"+(search==null?"":search)+"%");p.setString(i++,service);p.setString(i++,service);p.setString(i++,status);p.setString(i++,status);}else{p.setString(i++,"%"+(search==null?"":search)+"%");p.setString(i++,service);p.setString(i++,service);}try(ResultSet r=p.executeQuery()){List<Booking> out=new ArrayList<>();while(r.next())out.add(map(r));return out;}}catch(SQLException e){throw Database.failure(e);}}
    public Optional<Booking> byId(String id){try(Connection c=Database.connection();PreparedStatement p=c.prepareStatement("select * from bookings where lower(id)=lower(?)")){p.setString(1,id);try(ResultSet r=p.executeQuery()){return r.next()?Optional.of(map(r)):Optional.empty();}}catch(SQLException e){throw Database.failure(e);}}
    public boolean activeStaff(String employeeId){try(Connection c=Database.connection();PreparedStatement p=c.prepareStatement("select 1 from bookings where staff_id=? and status not in ('Completed','Rejected')")){p.setString(1,employeeId);try(ResultSet r=p.executeQuery()){return r.next();}}catch(SQLException e){throw Database.failure(e);}}
    public boolean hasActiveAssigned(String employeeId){return activeStaff(employeeId);}
    public int activeDemand(String station,ServiceType type){try(Connection c=Database.connection();PreparedStatement p=c.prepareStatement("select coalesce(sum(passenger_count),0) from bookings where station=? and service=? and status not in ('Completed','Rejected')")){p.setString(1,station);p.setString(2,type.label());try(ResultSet r=p.executeQuery()){r.next();return r.getInt(1);}}catch(SQLException e){throw Database.failure(e);}}
    public void insert(Connection c,Booking b)throws SQLException{try(PreparedStatement p=c.prepareStatement("insert into bookings(id,passenger_id,passenger,service,station,platform,pickup,drop_location,service_date,service_time,fare,gross_fare,discount,coupon_code,status,staff_id,train,bags,weight_rate,passenger_count) values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)")){int i=1;p.setString(i++,b.id());p.setString(i++,b.passengerId());p.setString(i++,b.passenger());p.setString(i++,b.service().label());p.setString(i++,b.station());p.setString(i++,b.platform());p.setString(i++,b.pickup());p.setString(i++,b.drop());p.setDate(i++,java.sql.Date.valueOf(b.date()));p.setTime(i++,Time.valueOf(b.time()));p.setInt(i++,b.fare());p.setInt(i++,b.grossFare());p.setInt(i++,b.discount());p.setString(i++,b.couponCode());p.setString(i++,b.status().label());p.setString(i++,b.staffId());p.setString(i++,b.train());if(b.bags()==null)p.setNull(i++,Types.INTEGER);else p.setInt(i++,b.bags());if(b.weightRate()==null)p.setNull(i++,Types.INTEGER);else p.setInt(i++,b.weightRate());p.setInt(i,b.passengerCount());p.executeUpdate();}}
    public void updateStatus(String id,BookingStatus status,String staffId){try(Connection c=Database.connection();PreparedStatement p=c.prepareStatement("update bookings set status=?,staff_id=? where id=?")){p.setString(1,status.label());p.setString(2,staffId);p.setString(3,id);p.executeUpdate();}catch(SQLException e){throw Database.failure(e);}}
    public void deleteResource(String id){try(Connection c=Database.connection();PreparedStatement p=c.prepareStatement("delete from resources where id=?")){p.setString(1,id);p.executeUpdate();}catch(SQLException e){throw Database.failure(e);}}
    private Booking map(ResultSet r)throws SQLException{return new Booking(r.getString("id"),r.getString("passenger_id"),r.getString("passenger"),ServiceType.from(r.getString("service")),r.getString("station"),r.getString("platform"),r.getString("pickup"),r.getString("drop_location"),r.getDate("service_date").toLocalDate(),r.getTime("service_time").toLocalTime(),r.getInt("fare"),r.getInt("gross_fare"),r.getInt("discount"),r.getString("coupon_code"),BookingStatus.from(r.getString("status")),r.getString("staff_id"),r.getString("train"),(Integer)r.getObject("bags"),(Integer)r.getObject("weight_rate"),r.getInt("passenger_count"));}
}
