package com.ecoaccess.dao;
import java.sql.*;import java.util.*;import com.ecoaccess.model.*;import com.ecoaccess.model.Enums.*;
public class BookingDao {
 public List<Booking> list(String passengerId,String staffId,String search,String service,String status){if(service!=null&&service.isBlank())service=null;if(status!=null&&status.isBlank())status=null;String q="select * from bookings where (? is null or passenger_id=?) and (? is null or (staff_id=? or staff_id is null)) and lower(id||' '||passenger||' '||station) like lower(?) and (? is null or service=?) and (? is null or status=?) order by service_date desc,service_time desc";try(Connection c=Database.connection();PreparedStatement p=c.prepareStatement(q)){p.setString(1,passengerId);p.setString(2,passengerId);p.setString(3,staffId);p.setString(4,staffId);p.setString(5,"%"+search+"%");p.setString(6,service);p.setString(7,service);p.setString(8,status);p.setString(9,status);try(ResultSet r=p.executeQuery()){List<Booking>x=new ArrayList<>();while(r.next())x.add(map(r));return x;}}catch(SQLException e){throw Database.failure(e);}}
 public Optional<Booking> byId(String id){try(Connection c=Database.connection();PreparedStatement p=c.prepareStatement("select * from bookings where lower(id)=lower(?)")){p.setString(1,id);try(ResultSet r=p.executeQuery()){return r.next()?Optional.of(map(r)):Optional.empty();}}catch(SQLException e){throw Database.failure(e);}}
 public boolean activeStaff(String employeeId){try(Connection c=Database.connection();PreparedStatement p=c.prepareStatement("select 1 from bookings where staff_id=? and status not in ('Completed','Rejected')")){p.setString(1,employeeId);try(ResultSet r=p.executeQuery()){return r.next();}}catch(SQLException e){throw Database.failure(e);}}
 public int activeDemand(String station,ServiceType type){try(Connection c=Database.connection();PreparedStatement p=c.prepareStatement("select coalesce(sum(passenger_count),0) from bookings where station=? and service=? and status not in ('Completed','Rejected')")){p.setString(1,station);p.setString(2,type.label());try(ResultSet r=p.executeQuery()){r.next();return r.getInt(1);}}catch(SQLException e){throw Database.failure(e);}}
 public void insert(Connection c,Booking b)throws SQLException{try(PreparedStatement p=c.prepareStatement("insert into bookings(id,passenger_id,passenger,service,station,platform,pickup,drop_location,service_date,service_time,fare,gross_fare,discount,coupon_code,status,staff_id,train,bags,weight_rate,passenger_count) values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)")){p.setString(1,b.id());p.setString(2,b.passengerId());p.setString(3,b.passenger());p.setString(4,b.service().label());p.setString(5,b.station());p.setString(6,b.platform());p.setString(7,b.pickup());p.setString(8,b.drop());p.setDate(9,Date.valueOf(b.date()));p.setTime(10,Time.valueOf(b.time()));p.setInt(11,b.fare());p.setInt(12,b.grossFare());p.setInt(13,b.discount());p.setString(14,b.couponCode());p.setString(15,b.status().label());p.setString(16,b.staffId());p.setString(17,b.train());if(b.bags()==null)p.setNull(18,Types.INTEGER);else p.setInt(18,b.bags());if(b.weightRate()==null)p.setNull(19,Types.INTEGER);else p.setInt(19,b.weightRate());p.setInt(20,b.passengerCount());p.executeUpdate();}}
 public void updateStatus(String id,BookingStatus status,String staffId){try(Connection c=Database.connection();PreparedStatement p=c.prepareStatement("update bookings set status=?,staff_id=? where id=?")){p.setString(1,status.label());p.setString(2,staffId);p.setString(3,id);p.executeUpdate();}catch(SQLException e){throw Database.failure(e);}}
 public void deleteResource(String id){try(Connection c=Database.connection();PreparedStatement p=c.prepareStatement("delete from resources where id=?")){p.setString(1,id);p.executeUpdate();}catch(SQLException e){throw Database.failure(e);}}
 public List<Booking> all(String search,String service){if(service!=null&&service.isBlank())service=null;String q="select * from bookings where lower(id||' '||passenger||' '||station||' '||service) like lower(?) and (? is null or service=?) order by service_date desc,service_time desc";try(Connection c=Database.connection();PreparedStatement p=c.prepareStatement(q)){p.setString(1,"%"+search+"%");p.setString(2,service);p.setString(3,service);try(ResultSet r=p.executeQuery()){List<Booking>x=new ArrayList<>();while(r.next())x.add(map(r));return x;}}catch(SQLException e){throw Database.failure(e);}}
 private Booking map(ResultSet r)throws SQLException{return new Booking(r.getString("id"),r.getString("passenger_id"),r.getString("passenger"),ServiceType.valueOf(r.getString("service").replace(' ','_').toUpperCase()),r.getString("station"),r.getString("platform"),r.getString("pickup"),r.getString("drop_location"),r.getDate("service_date").toLocalDate(),r.getTime("service_time").toLocalTime(),r.getInt("fare"),r.getInt("gross_fare"),r.getInt("discount"),r.getString("coupon_code"),BookingStatus.valueOf(r.getString("status").replace(' ','_').toUpperCase()),r.getString("staff_id"),r.getString("train"),r.getObject("bags")==null?null:r.getInt("bags"),r.getObject("weight_rate")==null?null:r.getInt("weight_rate"),r.getInt("passenger_count"));}
}
