package com.ecoaccess.dao;
import java.sql.*;import java.util.*;import com.ecoaccess.model.Entities.*;import com.ecoaccess.model.Enums.*;
public class CatalogDao {
 public Optional<Ticket> ticket(String pnr){try(Connection c=Database.connection();PreparedStatement p=c.prepareStatement("select * from tickets where pnr=?")){p.setString(1,pnr);try(ResultSet r=p.executeQuery()){return r.next()?Optional.of(ticket(r)):Optional.empty();}}catch(SQLException e){throw Database.failure(e);}}
 public List<String> locations(String station){try(Connection c=Database.connection();PreparedStatement p=c.prepareStatement("select location_name from station_locations where station=? order by location_name")){p.setString(1,station);try(ResultSet r=p.executeQuery()){List<String>x=new ArrayList<>();while(r.next())x.add(r.getString(1));return x;}}catch(SQLException e){throw Database.failure(e);}}
 public Optional<Journey> journey(String passengerId){try(Connection c=Database.connection();PreparedStatement p=c.prepareStatement("select j.*,t.* from journey_validations j join tickets t on t.pnr=j.pnr where j.passenger_id=?")){p.setString(1,passengerId);try(ResultSet r=p.executeQuery()){return r.next()?Optional.of(new Journey(r.getString("id"),passengerId,ticket(r),r.getBoolean("valid"),r.getTimestamp("validated_at").toLocalDateTime())):Optional.empty();}}catch(SQLException e){throw Database.failure(e);}}
 public void upsertJourney(String id,String passengerId,Ticket t){try(Connection c=Database.connection();PreparedStatement p=c.prepareStatement("insert into journey_validations(id,passenger_id,pnr,valid,validated_at) values(?,?,?,true,current_timestamp) on conflict(passenger_id) do update set id=excluded.id,pnr=excluded.pnr,valid=true,validated_at=current_timestamp")){p.setString(1,id);p.setString(2,passengerId);p.setString(3,t.pnr());p.executeUpdate();}catch(SQLException e){throw Database.failure(e);}}
 private Ticket ticket(ResultSet r)throws SQLException{return new Ticket(r.getString("pnr"),r.getString("train"),r.getDate("journey_date").toLocalDate(),r.getTime("journey_time").toLocalTime(),r.getString("station"),r.getString("platform"),r.getString("origin"),r.getString("destination"),r.getString("coach"),r.getString("class_name"));}
}
