package com.ecoaccess.dao;
import java.sql.*;import java.time.*;import java.util.*;import com.ecoaccess.model.Entities.*;import com.ecoaccess.model.Enums.*;
public class OperationsDao {
 public Optional<Resource> resource(String station,ServiceType type){try(Connection c=Database.connection();PreparedStatement p=c.prepareStatement("select * from resources where lower(station)=lower(?) and service=?")){p.setString(1,station);p.setString(2,type.label());try(ResultSet r=p.executeQuery()){return r.next()?Optional.of(resource(r)):Optional.empty();}}catch(SQLException e){throw Database.failure(e);}}
 public List<Resource> resources(String search){try(Connection c=Database.connection();PreparedStatement p=c.prepareStatement("select * from resources where lower(station) like lower(?) order by station,service")){p.setString(1,"%"+search+"%");try(ResultSet r=p.executeQuery()){List<Resource>x=new ArrayList<>();while(r.next())x.add(resource(r));return x;}}catch(SQLException e){throw Database.failure(e);}}
 public void addOrMergeResource(String id,String station,ServiceType type,int qty){try(Connection c=Database.connection();PreparedStatement p=c.prepareStatement("insert into resources(id,station,service,quantity) values(?,?,?,?) on conflict (station,service) do update set quantity=resources.quantity+excluded.quantity")){p.setString(1,id);p.setString(2,station);p.setString(3,type.label());p.setInt(4,qty);p.executeUpdate();}catch(SQLException e){throw Database.failure(e);}}
 public void updateResource(String id,int qty){try(Connection c=Database.connection();PreparedStatement p=c.prepareStatement("update resources set quantity=? where id=?")){p.setInt(1,qty);p.setString(2,id);p.executeUpdate();}catch(SQLException e){throw Database.failure(e);}}
 public void deleteResource(String id){try(Connection c=Database.connection();PreparedStatement p=c.prepareStatement("delete from resources where id=?")){p.setString(1,id);p.executeUpdate();}catch(SQLException e){throw Database.failure(e);}}
 public void insertWaste(Connection c,Waste w)throws SQLException{try(PreparedStatement p=c.prepareStatement("insert into waste_submissions(id,passenger_id,passenger,status,reward_points,photo_path,submitted_at,station,platform) values(?,?,?,?,?,?,?,?,?)")){p.setString(1,w.id());p.setString(2,w.passengerId());p.setString(3,w.passenger());p.setString(4,w.status().label());p.setInt(5,w.rewardPoints());p.setString(6,w.photoPath());p.setTimestamp(7,Timestamp.valueOf(w.submittedAt()));p.setString(8,w.station());p.setString(9,w.platform());p.executeUpdate();}}
 public Optional<Waste> waste(String id){return wasteOne("select * from waste_submissions where id=?",id);} public Optional<Waste> lastWaste(String p){return wasteOne("select * from waste_submissions where passenger_id=? order by submitted_at desc limit 1",p);}
 private Optional<Waste>wasteOne(String q,String x){try(Connection c=Database.connection();PreparedStatement p=c.prepareStatement(q)){p.setString(1,x);try(ResultSet r=p.executeQuery()){return r.next()?Optional.of(waste(r)):Optional.empty();}}catch(SQLException e){throw Database.failure(e);}}
 public List<Waste>wastes(String passengerId,String search){try(Connection c=Database.connection();PreparedStatement p=c.prepareStatement("select * from waste_submissions where (? is null or passenger_id=?) and lower(id||' '||passenger) like lower(?) order by submitted_at desc")){p.setString(1,passengerId);p.setString(2,passengerId);p.setString(3,"%"+search+"%");try(ResultSet r=p.executeQuery()){List<Waste>x=new ArrayList<>();while(r.next())x.add(waste(r));return x;}}catch(SQLException e){throw Database.failure(e);}}
 public void reviewWaste(Connection c,String id,WasteStatus s,String remark)throws SQLException{try(PreparedStatement p=c.prepareStatement("update waste_submissions set status=?,reward_points=?,reviewed_at=current_timestamp,remark=? where id=?")){p.setString(1,s.label());p.setInt(2,s==WasteStatus.ACCEPTED?20:0);p.setString(3,remark);p.setString(4,id);p.executeUpdate();}}
 public void insertCoupon(Connection c,Coupon x)throws SQLException{try(PreparedStatement p=c.prepareStatement("insert into coupons(id,code,passenger_id,passenger,points_redeemed,value,remaining,status,created_at,expires_at) values(?,?,?,?,?,?,?,?,?,?)")){p.setString(1,x.id());p.setString(2,x.code());p.setString(3,x.passengerId());p.setString(4,x.passenger());p.setInt(5,x.pointsRedeemed());p.setInt(6,x.value());p.setInt(7,x.remaining());p.setString(8,x.status().label());p.setTimestamp(9,Timestamp.valueOf(x.createdAt()));p.setTimestamp(10,Timestamp.valueOf(x.expiresAt()));p.executeUpdate();}}
 public Optional<Coupon> coupon(String code){try(Connection c=Database.connection();PreparedStatement p=c.prepareStatement("select * from coupons where code=?")){p.setString(1,code);try(ResultSet r=p.executeQuery()){return r.next()?Optional.of(coupon(r)):Optional.empty();}}catch(SQLException e){throw Database.failure(e);}}
 public List<Coupon> coupons(String passengerId,String search){expireCoupons();try(Connection c=Database.connection();PreparedStatement p=c.prepareStatement("select * from coupons where (? is null or passenger_id=?) and lower(code||' '||passenger) like lower(?) order by created_at desc")){p.setString(1,passengerId);p.setString(2,passengerId);p.setString(3,"%"+search+"%");try(ResultSet r=p.executeQuery()){List<Coupon>x=new ArrayList<>();while(r.next())x.add(coupon(r));return x;}}catch(SQLException e){throw Database.failure(e);}}
 public void spendCoupon(Connection c,Coupon x,int take,String usedFor,String usedOn)throws SQLException{int remain=x.remaining()-take;try(PreparedStatement p=c.prepareStatement("update coupons set remaining=?,status=?,used_at=current_timestamp,used_for=?,used_on=? where id=?")){p.setInt(1,remain);p.setString(2,remain==0?"Used":"Active");p.setString(3,usedFor);p.setString(4,usedOn);p.setString(5,x.id());p.executeUpdate();}}
 public void expireCoupons(){try(Connection c=Database.connection();PreparedStatement p=c.prepareStatement("update coupons set status='Expired' where status='Active' and expires_at < current_timestamp")){p.executeUpdate();}catch(SQLException e){throw Database.failure(e);}}
 public void insertRedemption(Connection c,Redemption x)throws SQLException{try(PreparedStatement p=c.prepareStatement("insert into redemptions(id,passenger_id,passenger,reward_name,points,coupon_code,coupon_value,status,redemption_date,created_at,expires_at) values(?,?,?,?,?,?,?,?,?,?,?)")){p.setString(1,x.id());p.setString(2,x.passengerId());p.setString(3,x.passenger());p.setString(4,x.rewardName());p.setInt(5,x.points());p.setString(6,x.couponCode());p.setInt(7,x.couponValue());p.setString(8,x.status());p.setDate(9,java.sql.Date.valueOf(x.date()));p.setTimestamp(10,Timestamp.valueOf(x.createdAt()));p.setTimestamp(11,Timestamp.valueOf(x.expiresAt()));p.executeUpdate();}}
 public List<Redemption> redemptions(String search){try(Connection c=Database.connection();PreparedStatement p=c.prepareStatement("select * from redemptions where lower(id||' '||passenger||' '||coupon_code) like lower(?) order by created_at desc")){p.setString(1,"%"+search+"%");try(ResultSet r=p.executeQuery()){List<Redemption>x=new ArrayList<>();while(r.next())x.add(redemption(r));return x;}}catch(SQLException e){throw Database.failure(e);}}
 public Optional<Redemption> redemption(String id){try(Connection c=Database.connection();PreparedStatement p=c.prepareStatement("select * from redemptions where id=?")){p.setString(1,id);try(ResultSet r=p.executeQuery()){return r.next()?Optional.of(redemption(r)):Optional.empty();}}catch(SQLException e){throw Database.failure(e);}}
 public void updateRedemptionStatus(Connection c,String id,String status)throws SQLException{try(PreparedStatement p=c.prepareStatement("update redemptions set status=? where id=?")){p.setString(1,status);p.setString(2,id);p.executeUpdate();}}
 public void insertCase(CaseRecord x){try(Connection c=Database.connection();PreparedStatement p=c.prepareStatement("insert into cases(id,type,passenger_id,passenger,booking_id,rating,subject,description,status,created_at) values(?,?,?,?,?,?,?,?,?,?)")){p.setString(1,x.id());p.setString(2,x.type().label());p.setString(3,x.passengerId());p.setString(4,x.passenger());p.setString(5,x.bookingId());p.setInt(6,x.rating());p.setString(7,x.subject());p.setString(8,x.description());p.setString(9,x.status());p.setTimestamp(10,Timestamp.valueOf(x.createdAt()));p.executeUpdate();}catch(SQLException e){throw Database.failure(e);}}
 public List<CaseRecord> cases(String passengerId,boolean complaintsOnly,String search){String q="select * from cases where (? is null or passenger_id=?) and (?=false or type='Complaint') and lower(id||' '||subject||' '||passenger) like lower(?) order by created_at desc";try(Connection c=Database.connection();PreparedStatement p=c.prepareStatement(q)){p.setString(1,passengerId);p.setString(2,passengerId);p.setBoolean(3,complaintsOnly);p.setString(4,"%"+search+"%");try(ResultSet r=p.executeQuery()){List<CaseRecord>x=new ArrayList<>();while(r.next())x.add(caseRecord(r));return x;}}catch(SQLException e){throw Database.failure(e);}}
 public void updateCaseStatus(String id,String status){try(Connection c=Database.connection();PreparedStatement p=c.prepareStatement("update cases set status=? where id=?")){p.setString(1,status);p.setString(2,id);p.executeUpdate();}catch(SQLException e){throw Database.failure(e);}}
 private Resource resource(ResultSet r)throws SQLException{return new Resource(r.getString("id"),r.getString("station"),ServiceType.from(r.getString("service")),r.getInt("quantity"));}
 private Waste waste(ResultSet r)throws SQLException{return new Waste(r.getString("id"),r.getString("passenger_id"),r.getString("passenger"),WasteStatus.valueOf(r.getString("status").toUpperCase()),r.getInt("reward_points"),r.getString("photo_path"),r.getTimestamp("submitted_at").toLocalDateTime(),r.getTimestamp("reviewed_at")==null?null:r.getTimestamp("reviewed_at").toLocalDateTime(),r.getString("remark"),r.getString("station"),r.getString("platform"));}
 private Coupon coupon(ResultSet r)throws SQLException{return new Coupon(r.getString("id"),r.getString("code"),r.getString("passenger_id"),r.getString("passenger"),r.getInt("points_redeemed"),r.getInt("value"),r.getInt("remaining"),CouponStatus.valueOf(r.getString("status").toUpperCase()),r.getTimestamp("created_at").toLocalDateTime(),r.getTimestamp("expires_at").toLocalDateTime(),r.getTimestamp("used_at")==null?null:r.getTimestamp("used_at").toLocalDateTime(),r.getString("used_for"),r.getString("used_on"));}
 private Redemption redemption(ResultSet r)throws SQLException{return new Redemption(r.getString("id"),r.getString("passenger_id"),r.getString("passenger"),r.getString("reward_name"),r.getInt("points"),r.getString("coupon_code"),r.getInt("coupon_value"),r.getString("status"),r.getDate("redemption_date").toLocalDate(),r.getTimestamp("created_at").toLocalDateTime(),r.getTimestamp("expires_at").toLocalDateTime());}
 private CaseRecord caseRecord(ResultSet r)throws SQLException{return new CaseRecord(r.getString("id"),ComplaintType.valueOf(r.getString("type").toUpperCase()),r.getString("passenger_id"),r.getString("passenger"),r.getString("booking_id"),r.getInt("rating"),r.getString("subject"),r.getString("description"),r.getString("status"),r.getTimestamp("created_at").toLocalDateTime());}
}
