package com.ecoaccess.dao;
import java.sql.*;import java.time.*;import java.util.*;import com.ecoaccess.model.*;import com.ecoaccess.model.Enums.*;
public class OperationsDao {
 public Optional<Resource> resource(String station,ServiceType type){try(Connection c=Database.connection();PreparedStatement p=c.prepareStatement("select * from resources where lower(station)=lower(?) and service=?")){p.setString(1,station);p.setString(2,type.label());try(ResultSet r=p.executeQuery()){return r.next()?Optional.of(resource(r)):Optional.empty();}}catch(SQLException e){throw Database.failure(e);}}
 public List<Resource> resources(String search){try(Connection c=Database.connection();PreparedStatement p=c.prepareStatement("select * from resources where lower(station) like lower(?) order by station,service")){p.setString(1,"%"+search+"%");try(ResultSet r=p.executeQuery()){List<Resource>x=new ArrayList<>();while(r.next())x.add(resource(r));return x;}}catch(SQLException e){throw Database.failure(e);}}
 public void addOrMergeResource(String id,String station,ServiceType type,int qty){try(Connection c=Database.connection();PreparedStatement p=c.prepareStatement("insert into resources(id,station,service,quantity) values(?,?,?,?) on conflict (station,service) do update set quantity=resources.quantity+excluded.quantity")){p.setString(1,id);p.setString(2,station);p.setString(3,type.label());p.setInt(4,qty);p.executeUpdate();}catch(SQLException e){throw Database.failure(e);}}
 public void updateResource(String id,int qty){try(Connection c=Database.connection();PreparedStatement p=c.prepareStatement("update resources set quantity=? where id=?")){p.setInt(1,qty);p.setString(2,id);p.executeUpdate();}catch(SQLException e){throw Database.failure(e);}}
 public void deleteResource(String id){try(Connection c=Database.connection();PreparedStatement p=c.prepareStatement("delete from resources where id=?")){p.setString(1,id);p.executeUpdate();}catch(SQLException e){throw Database.failure(e);}}
 public void insertWaste(Connection c,Waste w)throws SQLException{try(PreparedStatement p=c.prepareStatement("insert into waste_submissions(id,passenger_id,passenger,status,reward_points,photo_path,submitted_at,station,platform) values(?,?,?,?,?,?,?,?,?)")){p.setString(1,w.id());p.setString(2,w.passengerId());p.setString(3,w.passenger());p.setString(4,w.status().label());p.setInt(5,w.rewardPoints());p.setString(6,w.photoPath());p.setTimestamp(7,Timestamp.valueOf(w.submittedAt()));p.setString(8,w.station());p.setString(9,w.platform());p.executeUpdate();}}
 public Optional<Waste> waste(String id){return wasteOne("select * from waste_submissions where id=?",id);} public Optional<Waste> lastWaste(String p){return wasteOne("select * from waste_submissions where passenger_id=? order by submitted_at desc limit 1",p);}
 private Optional<Waste>wasteOne(String q,String x){try(Connection c=Database.connection();PreparedStatement p=c.prepareStatement(q)){p.setString(1,x);try(ResultSet r=p.executeQuery()){return r.next()?Optional.of(waste(r)):Optional.empty();}}catch(SQLException e){throw Database.failure(e);}}
 private Resource resource(ResultSet r)throws SQLException{return new Resource(r.getString("id"),r.getString("station"),ServiceType.valueOf(r.getString("service").replace(' ','_').toUpperCase()),r.getInt("quantity"));}
 private Waste waste(ResultSet r)throws SQLException{return new Waste(r.getString("id"),r.getString("passenger_id"),r.getString("passenger"),WasteStatus.valueOf(r.getString("status").toUpperCase()),r.getInt("reward_points"),r.getString("photo_path"),r.getTimestamp("submitted_at").toLocalDateTime(),r.getTimestamp("reviewed_at")==null?null:r.getTimestamp("reviewed_at").toLocalDateTime(),r.getString("remark"),r.getString("station"),r.getString("platform"));}
}
