package com.ecoaccess.service;
import java.sql.*;import java.util.*;import com.ecoaccess.dao.*;import com.ecoaccess.exception.AppExceptions.*;import com.ecoaccess.model.Entities.*;import com.ecoaccess.model.Enums.*;import com.ecoaccess.util.*;
public class AuthService {private final AccountDao accounts=new AccountDao();
 public Passenger register(String name,String mobile,String email,String password,String confirm,String otp){name=Validation.name(name);mobile=Validation.mobile(mobile);email=Validation.email(email);Validation.password(password);if(!password.equals(confirm))throw new ValidationException("Passwords do not match.");if(!"123456".equals(otp))throw new ValidationException("Use demo OTP 123456.");if(accounts.passengerByMobile(mobile).isPresent())throw new BusinessRuleException("Mobile already registered.");Passenger p=new Passenger(Ids.next("P"),name,mobile,email,Passwords.hash(password),0);try(Connection c=Database.connection()){accounts.insertPassenger(c,p);return p;}catch(SQLException e){throw Database.failure(e);}}
 public Object login(Role role,String identity,String password){Validation.required(password,"Password is required.");return switch(role){case PASSENGER->{String mobile=Validation.mobile(identity);Passenger p=accounts.passengerByMobile(mobile).orElseThrow(()->new AuthenticationException("No account found with this mobile."));if(!Passwords.matches(password,p.passwordHash()))throw new AuthenticationException("Incorrect password.");yield p;}case STAFF->{Staff s=accounts.staffByEmployeeId(Validation.required(identity,"Employee ID is required.")).orElseThrow(()->new AuthenticationException("No account found with this Employee ID."));if(!Passwords.matches(password,s.passwordHash()))throw new AuthenticationException("Incorrect password.");yield s;}case ADMIN->{Admin a=accounts.adminByEmail(Validation.email(identity)).orElseThrow(()->new AuthenticationException("No account found with this email."));if(!Passwords.matches(password,a.passwordHash()))throw new AuthenticationException("Incorrect password.");yield a;}};}
 public void reset(Role role,String identity,String password){if(role==Role.ADMIN)throw new AuthorizationException("Admin password reset is not available.");Validation.password(password);if(role==Role.PASSENGER){Passenger p=accounts.passengerByMobile(Validation.mobile(identity)).orElseThrow(()->new NotFoundException("No account found with this identity."));updatePassenger(new Passenger(p.id(),p.name(),p.mobile(),p.email(),Passwords.hash(password),p.points()));}else{Staff s=accounts.staffByEmployeeId(Validation.required(identity,"Employee ID is required.")).orElseThrow(()->new NotFoundException("No account found with this identity."));accounts.updateStaff(new Staff(s.id(),s.employeeId(),s.name(),Passwords.hash(password),s.jobRole(),s.status()));}}
 public void updatePassenger(Passenger p){try(Connection c=Database.connection()){accounts.updatePassenger(c,p);}catch(SQLException e){throw Database.failure(e);}}
 public AccountDao dao(){return accounts;}
}
