package com.ecoaccess.service;
import java.sql.*;import java.time.*;import java.util.*;import com.ecoaccess.dao.*;import com.ecoaccess.exception.AppExceptions.*;import com.ecoaccess.model.Entities.*;import com.ecoaccess.model.Enums.*;import com.ecoaccess.util.*;
public class OperationsService {private final AccountDao accounts;private final BookingDao bookings;private final OperationsDao ops;private final CatalogDao catalog;
 public OperationsService(AccountDao a,BookingDao b,OperationsDao o,CatalogDao c){accounts=a;bookings=b;ops=o;catalog=c;}
 public void staffAvailability(Staff s,boolean available){accounts.updateStaff(new Staff(s.id(),s.employeeId(),s.name(),s.passwordHash(),available?StaffStatus.AVAILABLE:StaffStatus.UNAVAILABLE));}
 public Booking staffAction(Staff s,String bookingId,boolean accept){Booking b=bookings.byId(bookingId).orElseThrow(()->new NotFoundException("Booking not found."));if(!(b.staffId()==null||b.staffId().equals(s.employeeId())))throw new AuthorizationException("This booking is assigned to another staff member.");if(b.status()!=BookingStatus.BOOKED&&b.status()!=BookingStatus.ASSIGNED)throw new BusinessRuleException("Booking cannot be accepted or rejected in its current status.");if(accept){requireAvailable(s);bookings.updateStatus(b.id(),BookingStatus.ACCEPTED,s.employeeId());}else bookings.updateStatus(b.id(),BookingStatus.REJECTED,b.staffId()==null?s.employeeId():b.staffId());return bookings.byId(b.id()).orElseThrow();}
 public Booking advance(Staff s,String bookingId){requireAvailable(s);Booking b=bookings.byId(bookingId).orElseThrow(()->new NotFoundException("Booking not found."));if(!s.employeeId().equals(b.staffId()))throw new AuthorizationException("Only the assigned staff member can update this booking.");BookingStatus next=switch(b.status()){case ACCEPTED->BookingStatus.REACHED_PASSENGER;case REACHED_PASSENGER->BookingStatus.SERVICE_STARTED;case SERVICE_STARTED->BookingStatus.COMPLETED;default->throw new BusinessRuleException("This booking cannot move to the next status.");};bookings.updateStatus(b.id(),next,s.employeeId());return bookings.byId(b.id()).orElseThrow();}
 private void requireAvailable(Staff s){if(s.status()!=StaffStatus.AVAILABLE)throw new BusinessRuleException("Please turn on your availability to \"Available\".");}
 public Waste submitWaste(Passenger p,String photo){Journey j=catalog.journey(p.id()).filter(Journey::valid).orElseThrow(()->new BusinessRuleException("Please validate your journey before continuing."));Validation.required(photo,"Take a picture of the waste disposal first.");Optional<Waste> last=ops.lastWaste(p.id());if(last.isPresent()&&last.get().submittedAt().plusHours(4).isAfter(LocalDateTime.now()))throw new BusinessRuleException("The next image can be taken after exactly 4 hours from the last submission.");Waste w=new Waste(Ids.next("WD"),p.id(),p.name(),WasteStatus.PENDING,0,photo,LocalDateTime.now(),null,null,j.ticket().station(),j.ticket().platform());try(Connection c=Database.connection()){ops.insertWaste(c,w);return w;}catch(SQLException e){throw Database.failure(e);}}
 public Waste reviewWaste(String id,boolean accept,String remark){Waste w=ops.waste(id).orElseThrow(()->new NotFoundException("Waste submission not found."));if(w.status()!=WasteStatus.PENDING)throw new BusinessRuleException("This waste submission has already been reviewed.");if(!accept)Validation.required(remark,"Enter a rejection remark.");try(Connection c=Database.connection()){c.setAutoCommit(false);try{ops.reviewWaste(c,id,accept?WasteStatus.ACCEPTED:WasteStatus.REJECTED,accept?null:remark);if(accept){Passenger p=accounts.passengerById(w.passengerId()).orElse(null);if(p!=null)accounts.updatePassenger(c,new Passenger(p.id(),p.name(),p.mobile(),p.email(),p.passwordHash(),p.points()+20));}c.commit();return ops.waste(id).orElseThrow();}catch(Exception e){c.rollback();if(e instanceof RuntimeException re)throw re;throw new DatabaseException("Unable to review waste submission.",e);}}catch(SQLException e){throw Database.failure(e);}}
 public Coupon redeem(Passenger p){if(p.points()<100)throw new BusinessRuleException("Redeem will be available once you reach 100 points.");int value=(int)Math.round(p.points()*.5);LocalDateTime now=LocalDateTime.now();Coupon c=new Coupon(Ids.next("CP"),Ids.next("EA"),p.id(),p.name(),0,value,value,CouponStatus.ACTIVE,now,now.plusDays(30),null,null,null);try(Connection c=Database.connection()){ops.insertCoupon(c);return c;}catch(SQLException e){throw Database.failure(e);}}
 public Coupon applyToTrain(Passenger p,String code){catalog.journey(p.id()).filter(Journey::valid).orElseThrow(()->new BusinessRuleException("Validate your journey first before applying a train coupon."));Coupon c=ops.coupon(code).orElseThrow(()->new NotFoundException("Coupon not found."));if(!c.passengerId().equals(p.id())||c.status()!=CouponStatus.ACTIVE||c.remaining()<=0||c.expiresAt().isBefore(LocalDateTime.now()))throw new BusinessRuleException("This coupon is expired or no longer available.");return c;}
 public void decidePendingRedemption(String id,boolean approve){Redemption r=ops.redemption(id).orElseThrow(()->new NotFoundException("Redemption not found."));if(!"Pending".equals(r.status()))throw new BusinessRuleException("Only pending redemptions can be approved or rejected.");try(Connection c=Database.connection()){c.setAutoCommit(false);try{ops.updateRedemptionStatus(c,id,approve?"Approved":"Rejected");if(!approve){Passenger p=accounts.passengerById(r.passengerId()).orElseThrow(()->new NotFoundException("Passenger not found."));accounts.updatePassenger(c,new Passenger(p.id(),p.name(),p.mobile(),p.email(),p.passwordHash(),p.points()+r.points()));}c.commit();}catch(Exception e){c.rollback();if(e instanceof RuntimeException re)throw re;throw new DatabaseException("Unable to update redemption.",e);}}catch(SQLException e){throw Database.failure(e);}}
 public CaseRecord submitCase(Passenger p,ComplaintType type,String bookingId,int rating,String subject,String description){Validation.range(rating,1,5,"Rating must be between 1 and 5.");subject=Validation.alphaText(subject,"Subject",80);description=Validation.alphaText(description,"Description",500);if(type==ComplaintType.COMPLAINT){if(bookingId==null||bookingId.isBlank())throw new ValidationException("Booking is required for a complaint.");Booking b=bookings.byId(bookingId).orElseThrow(()->new NotFoundException("Booking not found."));if(!b.passengerId().equals(p.id()))throw new AuthorizationException("Complaint booking must belong to you.");}CaseRecord x=new CaseRecord(Ids.next(type==ComplaintType.COMPLAINT?"CP":"FB"),type,p.id(),p.name(),bookingId,rating,subject,description,type==ComplaintType.COMPLAINT?"Open":"Submitted",LocalDateTime.now());ops.insertCase(x);return x;}
 public void complaintStatus(String id,boolean close){CaseRecord x=ops.cases(null,true,"").stream().filter(c->c.id().equalsIgnoreCase(id)).findFirst().orElseThrow(()->new NotFoundException("Complaint not found."));if(close){if("Closed".equals(x.status()))throw new BusinessRuleException("This complaint is already closed.");ops.updateCaseStatus(id,"Closed");}else{if(!"Open".equals(x.status()))throw new BusinessRuleException("Only open complaints can be resolved.");ops.updateCaseStatus(id,"Resolved");}}
 public Staff addStaff(String name){name=Validation.name(name);Staff s=new Staff(Ids.next("STF"),Ids.next("STF").replace("STF-","STF"),name,Passwords.hash("Test@123"),StaffStatus.AVAILABLE);accounts.insertStaff(s);return s;}
 public void editStaff(Staff s,String name){accounts.updateStaff(new Staff(s.id(),s.employeeId(),Validation.name(name),s.passwordHash(),s.status()));}
 public void deleteStaff(Staff s){if(bookings.hasActiveAssigned(s.employeeId()))throw new BusinessRuleException("Cannot delete staff with active assigned bookings.");accounts.deleteStaff(s.id());}
 public void resource(String station,ServiceType type,int qty){Validation.required(station,"Station is required.");if(qty<0)throw new ValidationException("Enter a valid quantity.");ops.addOrMergeResource(Ids.next("RS"),station.trim(),type,qty);} public void updateResource(String id,int qty){if(qty<0)throw new ValidationException("Enter a valid quantity.");ops.updateResource(id,qty);}
 public List<Waste>wastes(String passenger,String search){return ops.wastes(passenger,search);} public List<Coupon>coupons(String passenger,String search){return ops.coupons(passenger,search);} public List<CaseRecord>cases(String passenger,String search){return ops.cases(passenger,false,search);} public List<Redemption>redemptions(String search){return ops.redemptions(search);} 
}
