package com.ecoaccess.model;

import java.time.*; import com.ecoaccess.model.Enums.*;

public class Booking {
    private String id; private String passengerId; private String passenger; private ServiceType service; private String station; private String platform; private String pickup; private String drop; private LocalDate date; private LocalTime time; private int fare; private int grossFare; private int discount; private String couponCode; private BookingStatus status; private String staffId; private String train; private Integer bags; private Integer weightRate; private int passengerCount;
    public Booking() { }
    public Booking(String id,String passengerId,String passenger,ServiceType service,String station,String platform,String pickup,String drop,LocalDate date,LocalTime time,int fare,int grossFare,int discount,String couponCode,BookingStatus status,String staffId,String train,Integer bags,Integer weightRate,int passengerCount){this.id=id;this.passengerId=passengerId;this.passenger=passenger;this.service=service;this.station=station;this.platform=platform;this.pickup=pickup;this.drop=drop;this.date=date;this.time=time;this.fare=fare;this.grossFare=grossFare;this.discount=discount;this.couponCode=couponCode;this.status=status;this.staffId=staffId;this.train=train;this.bags=bags;this.weightRate=weightRate;this.passengerCount=passengerCount;}
    public String getId(){return id;} public void setId(String value){id=value;} public String getPassengerId(){return passengerId;} public void setPassengerId(String value){passengerId=value;} public String getPassenger(){return passenger;} public void setPassenger(String value){passenger=value;} public ServiceType getService(){return service;} public void setService(ServiceType value){service=value;} public String getStation(){return station;} public void setStation(String value){station=value;} public String getPlatform(){return platform;} public void setPlatform(String value){platform=value;} public String getPickup(){return pickup;} public void setPickup(String value){pickup=value;} public String getDrop(){return drop;} public void setDrop(String value){drop=value;} public LocalDate getDate(){return date;} public void setDate(LocalDate value){date=value;} public LocalTime getTime(){return time;} public void setTime(LocalTime value){time=value;} public int getFare(){return fare;} public void setFare(int value){fare=value;} public int getGrossFare(){return grossFare;} public void setGrossFare(int value){grossFare=value;} public int getDiscount(){return discount;} public void setDiscount(int value){discount=value;} public String getCouponCode(){return couponCode;} public void setCouponCode(String value){couponCode=value;} public BookingStatus getStatus(){return status;} public void setStatus(BookingStatus value){status=value;} public String getStaffId(){return staffId;} public void setStaffId(String value){staffId=value;} public String getTrain(){return train;} public void setTrain(String value){train=value;} public Integer getBags(){return bags;} public void setBags(Integer value){bags=value;} public Integer getWeightRate(){return weightRate;} public void setWeightRate(Integer value){weightRate=value;} public int getPassengerCount(){return passengerCount;} public void setPassengerCount(int value){passengerCount=value;}
}
