package com.ecoaccess.model;

import java.time.*; import com.ecoaccess.model.Enums.ServiceType;

public class BookingRequest {
    private String pnr; private String train; private LocalDate date; private LocalTime time; private String station; private ServiceType service; private int passengerCount; private Integer bags; private Integer weightRate; private String pickup; private String drop; private String couponCode; private String paymentMethod; private String cardName; private String cardNumber; private String cardExpiry; private String cvv;
    public BookingRequest() { }
    public BookingRequest(String pnr,String train,LocalDate date,LocalTime time,String station,ServiceType service,int passengerCount,Integer bags,Integer weightRate,String pickup,String drop,String couponCode,String paymentMethod,String cardName,String cardNumber,String cardExpiry,String cvv){this.pnr=pnr;this.train=train;this.date=date;this.time=time;this.station=station;this.service=service;this.passengerCount=passengerCount;this.bags=bags;this.weightRate=weightRate;this.pickup=pickup;this.drop=drop;this.couponCode=couponCode;this.paymentMethod=paymentMethod;this.cardName=cardName;this.cardNumber=cardNumber;this.cardExpiry=cardExpiry;this.cvv=cvv;}
    public String getPnr(){return pnr;} public void setPnr(String value){pnr=value;} public String getTrain(){return train;} public void setTrain(String value){train=value;} public LocalDate getDate(){return date;} public void setDate(LocalDate value){date=value;} public LocalTime getTime(){return time;} public void setTime(LocalTime value){time=value;} public String getStation(){return station;} public void setStation(String value){station=value;} public ServiceType getService(){return service;} public void setService(ServiceType value){service=value;} public int getPassengerCount(){return passengerCount;} public void setPassengerCount(int value){passengerCount=value;} public Integer getBags(){return bags;} public void setBags(Integer value){bags=value;} public Integer getWeightRate(){return weightRate;} public void setWeightRate(Integer value){weightRate=value;} public String getPickup(){return pickup;} public void setPickup(String value){pickup=value;} public String getDrop(){return drop;} public void setDrop(String value){drop=value;} public String getCouponCode(){return couponCode;} public void setCouponCode(String value){couponCode=value;} public String getPaymentMethod(){return paymentMethod;} public void setPaymentMethod(String value){paymentMethod=value;} public String getCardName(){return cardName;} public void setCardName(String value){cardName=value;} public String getCardNumber(){return cardNumber;} public void setCardNumber(String value){cardNumber=value;} public String getCardExpiry(){return cardExpiry;} public void setCardExpiry(String value){cardExpiry=value;} public String getCvv(){return cvv;} public void setCvv(String value){cvv=value;}
}
