package com.ecoaccess.model;

import java.time.LocalDateTime; import com.ecoaccess.model.Enums.CouponStatus;

public class Coupon {
    private String id; private String code; private String passengerId; private String passenger; private int pointsRedeemed; private int value; private int remaining; private CouponStatus status; private LocalDateTime createdAt; private LocalDateTime expiresAt; private LocalDateTime usedAt; private String usedFor; private String usedOn;
    public Coupon() { }
    public Coupon(String id,String code,String passengerId,String passenger,int pointsRedeemed,int value,int remaining,CouponStatus status,LocalDateTime createdAt,LocalDateTime expiresAt,LocalDateTime usedAt,String usedFor,String usedOn){this.id=id;this.code=code;this.passengerId=passengerId;this.passenger=passenger;this.pointsRedeemed=pointsRedeemed;this.value=value;this.remaining=remaining;this.status=status;this.createdAt=createdAt;this.expiresAt=expiresAt;this.usedAt=usedAt;this.usedFor=usedFor;this.usedOn=usedOn;}
    public String getId(){return id;} public void setId(String value){id=value;} public String getCode(){return code;} public void setCode(String value){code=value;} public String getPassengerId(){return passengerId;} public void setPassengerId(String value){passengerId=value;} public String getPassenger(){return passenger;} public void setPassenger(String value){passenger=value;} public int getPointsRedeemed(){return pointsRedeemed;} public void setPointsRedeemed(int value){pointsRedeemed=value;} public int getValue(){return value;} public void setValue(int value){value=value;} public int getRemaining(){return remaining;} public void setRemaining(int value){remaining=value;} public CouponStatus getStatus(){return status;} public void setStatus(CouponStatus value){status=value;} public LocalDateTime getCreatedAt(){return createdAt;} public void setCreatedAt(LocalDateTime value){createdAt=value;} public LocalDateTime getExpiresAt(){return expiresAt;} public void setExpiresAt(LocalDateTime value){expiresAt=value;} public LocalDateTime getUsedAt(){return usedAt;} public void setUsedAt(LocalDateTime value){usedAt=value;} public String getUsedFor(){return usedFor;} public void setUsedFor(String value){usedFor=value;} public String getUsedOn(){return usedOn;} public void setUsedOn(String value){usedOn=value;}

    public String id(){return id;} public String code(){return code;} public String passengerId(){return passengerId;} public String passenger(){return passenger;} public int pointsRedeemed(){return pointsRedeemed;} public int value(){return value;} public int remaining(){return remaining;} public CouponStatus status(){return status;} public LocalDateTime createdAt(){return createdAt;} public LocalDateTime expiresAt(){return expiresAt;} public LocalDateTime usedAt(){return usedAt;} public String usedFor(){return usedFor;} public String usedOn(){return usedOn;}
}
